README.md
lamini/__init__.py
lamini/api/lamini.py
lamini/api/rest_requests.py
lamini/api/train.py
lamini/api/utils/async_inference_queue.py
lamini/api/utils/async_inference_queue_3_10.py
lamini/api/utils/base_async_inference_queue.py
lamini/api/utils/completion.py
lamini/api/utils/process_batch.py
lamini/api/utils/reservations.py
lamini/api/utils/shutdown.py
lamini/api/utils/upload_client.py
lamini/error/error.py
lamini/runners/base_runner.py
lamini/runners/basic_model_runner.py
lamini/runners/llama_v2_runner.py
lamini/runners/mistral_runner.py
pyproject.toml

[Github Action] Update code to 2.0.12a1

---

lamini/api/lamini.py
lamini/api/train.py
lamini/api/utils/async_inference_queue.py
lamini/api/utils/async_inference_queue_3_10.py
lamini/api/utils/base_async_inference_queue.py
lamini/api/utils/process_batch.py
lamini/api/utils/reservations.py
lamini/runners/base_runner.py
pyproject.toml

[Github Action] Update code to 2.0.15

---

lamini/api/lamini.py
lamini/api/train.py
pyproject.toml

[Github Action] Update code to 2.0.16

---

lamini/__init__.py
lamini/api/lamini.py
lamini/api/rest_requests.py
lamini/api/train.py
lamini/api/utils/reservations.py
lamini/classify/llama_classifier.py
lamini/generation/base_generation_queue.py
lamini/generation/base_node_object.py
lamini/generation/base_prompt_object.py
lamini/generation/generation_node.py
lamini/generation/generation_pipeline.py
lamini/generation/generation_queue_3_10.py
lamini/generation/modify_node.py
lamini/generation/process_generation_batch.py
lamini/generation/split_response_node.py
pyproject.toml

[Github Action] Update code to 2.1.1

---

lamini/__init__.py
lamini/api/lamini.py
lamini/api/precise_trainer.py
lamini/api/streaming_completion.py
lamini/api/train.py
lamini/api/utils/completion.py
lamini/generation/base_prompt_object.py
pyproject.toml

[Github Action] Update code to 2.1.2

---

lamini/api/lamini.py
lamini/api/precise_trainer.py
lamini/api/rest_requests.py
lamini/api/train.py
lamini/api/utils/async_inference_queue.py
lamini/api/utils/async_inference_queue_3_10.py
lamini/api/utils/base_async_inference_queue.py
lamini/api/utils/reservations.py
lamini/api/utils/upload_client.py
lamini/generation/embedding_node.py
lamini/generation/generation_node.py
lamini/generation/generation_pipeline.py
lamini/generation/generation_queue_3_10.py
lamini/generation/process_generation_batch.py
lamini/generation/token_optimizer.py
lamini/runners/base_runner.py
lamini/runners/llama_v2_runner.py
lamini/runners/mistral_runner.py
pyproject.toml

[Github Action] Update code to 2.1.4

---

pyproject.toml

[Github Action] Update code to 2.1.6

---

lamini/__init__.py
lamini/api/lamini.py
lamini/api/precise_trainer.py
lamini/api/streaming_completion.py
lamini/api/train.py
lamini/api/utils/upload_client.py
lamini/classify/lamini_classifier.py
lamini/generation/generation_node.py
lamini/generation/process_generation_batch.py
lamini/runners/llama_v2_runner.py
lamini/runners/llama_v3_runner.py
pyproject.toml

[Github Action] Update code to 2.2.0

---

lamini/api/memory_trainer.py
lamini/api/streaming_completion.py
lamini/api/utils/async_inference_queue_3_10.py
lamini/api/utils/reservations.py
pyproject.toml

[Github Action] Update code to 2.2.1

---

lamini/api/lamini.py
lamini/api/memory_trainer.py
lamini/api/rest_requests.py
lamini/api/train.py
lamini/classify/lamini_classifier.py
lamini/runners/base_runner.py
pyproject.toml

[Github Action] Update code to 2.5.2

---

lamini/api/rest_requests.py
pyproject.toml

[Github Action] Update code to 2.5.3

---

pyproject.toml

[Github Action] Update code to 2.5.4

---

lamini/classify/lamini_classifier.py

- Removed calls to LlamaV2Runner within DefaultGenerators
- Removed ThreadPoolExecutor within prompt_train
- Small variable changes to fix recent updates

Refactoring of lamini_classifier 

---

lamini/__init__.py
lamini/api/utils/async_inference_queue_3_10.py
lamini/api/utils/reservations.py
lamini/generation/base_generation_queue.py
lamini/generation/base_prompt_object.py
lamini/generation/generation_node.py
lamini/generation/generation_queue_3_10.py
lamini/generation/process_generation_batch.py
pyproject.toml

[Github Action] Update code to 2.5.6

---

lamini/api/rest_requests.py
pyproject.toml

[Github Action] Update code to 2.5.7

---

lamini/__init__.py
lamini/api/classifier.py
lamini/api/embedding.py
lamini/api/lamini.py
lamini/api/rest_requests.py
lamini/api/streaming_completion.py
lamini/api/train.py
lamini/api/utils/completion.py
lamini/api/utils/reservations.py
lamini/classify/lamini_classifier.py
lamini/evaluators/benchmark.py
lamini/evaluators/custom/earnings_call_evaluator.py
lamini/evaluators/custom/ecommerce_evaluator.py
lamini/evaluators/custom/icd_evaluator.py
lamini/generation/base_generation_queue.py
lamini/generation/base_prompt_object.py
lamini/generation/embedding_node.py
lamini/generation/generation_node.py
lamini/generation/generation_pipeline.py
lamini/generation/generation_queue_3_10.py
lamini/generation/process_generation_batch.py
lamini/index/lamini_index.py
lamini/runners/base_runner.py
lamini/runners/llama_v2_runner.py
lamini/runners/llama_v3_runner.py
lamini/runners/mistral_runner.py
pyproject.toml

[Github Action] Update code to 3.0.0

---

lamini/api/utils/completion.py
lamini/api/utils/reservations.py
lamini/classify/lamini_classifier.py
lamini/generation/classifier_node.py
lamini/generation/embedding_node.py
lamini/generation/index_node.py
lamini/generation/process_generation_batch.py
pyproject.toml

[Github Action] Update code to 3.0.4

---

lamini/__init__.py
lamini/api/lamini.py
lamini/api/train.py
lamini/api/utils/completion.py
lamini/api/utils/iterators.py
lamini/api/utils/reservations.py
lamini/api/utils/shutdown.py
lamini/api/utils/upload_client.py
lamini/generation/process_generation_batch.py
pyproject.toml

[Github Action] Update code to 3.0.5

---

lamini/__init__.py
lamini/api/classifier.py
lamini/api/embedding.py
lamini/api/lamini.py
lamini/api/lamini_config.py
lamini/api/rest_requests.py
lamini/api/streaming_completion.py
lamini/api/synchronize.py
lamini/api/train.py
lamini/api/utils/batch.py
lamini/api/utils/iterators.py
lamini/api/utils/reservations.py
lamini/api/utils/shutdown.py
lamini/api/utils/upload_client.py
lamini/classify/lamini_classifier.py
lamini/error/error.py
lamini/evaluators/helm/mmlu_evaluator.py
lamini/generation/base_prompt_object.py
lamini/generation/classifier_node.py
lamini/generation/embedding_node.py
lamini/generation/index_node.py
lamini/generation/process_generation_batch.py
pyproject.toml

[Github Action] Update code to 3.1.0

---

README.md
lamini/__init__.py
lamini/api/classifier.py
lamini/api/lamini.py
lamini/api/lamini_config.py
lamini/api/model_downloader.py
lamini/api/pipeline_client.py
lamini/api/rest_requests.py
lamini/api/streaming_completion.py
lamini/api/train.py
lamini/api/utils/batch_completions.py
lamini/api/utils/batch_embeddings.py
lamini/api/utils/supported_models.py
lamini/api/versions.py
lamini/classify/lamini_classifier.py
lamini/error/error.py
lamini/evaluators/custom/earnings_call_evaluator.py
lamini/evaluators/helm/harness_evaluator.py
lamini/generation/base_generation_queue.py
lamini/generation/base_prompt_object.py
lamini/generation/embedding_node.py
lamini/generation/generation_node.py
lamini/generation/generation_pipeline.py
lamini/generation/llm_stream.py
lamini/generation/modify_node.py
lamini/generation/process_generation_batch.py
lamini/generation/split_response_node.py
pyproject.toml

[Github Action] Update code to 3.1.3

---

lamini/__init__.py
lamini/api/memory_rag.py
lamini/api/rest_requests.py
pyproject.toml

[Github Action] Update code to 3.2.5

---

lamini/__init__.py
lamini/api/memory_rag.py
pyproject.toml

[Github Action] Update code to 3.2.6

---

LICENSE
lamini/__init__.py
lamini/api/embedding.py
lamini/api/train.py
lamini/api/utils/supported_models.py
lamini/experiment/__init__.py
lamini/experiment/base_experiment_object.py
lamini/experiment/base_memory_experiment.py
lamini/experiment/generators/__init__.py
lamini/experiment/generators/save_generator.py
lamini/experiment/pipeline/base_agentic_pipeline.py
lamini/experiment/utils/__init__.py
lamini/experiment/utils/text_handling.py
lamini/experiment/validators/sql_autofix.py
lamini/experiment/validators/sql_validator.py
pyproject.toml

[Github Action] Update code to 3.2.18

---

lamini/experiment/__init__.py
lamini/experiment/base_experiment_object.py
lamini/experiment/base_generator.py
lamini/experiment/generators/save_generator.py
lamini/experiment/pipeline/base_agentic_pipeline.py
lamini/experiment/validators/sql_autofix.py
lamini/experiment/validators/sql_validator.py
pyproject.toml

[Github Action] Update code to 3.2.20
